name: money_manager_app
description: "Money Manager mobile app built with Flutter and Firebase"
publish_to: 'none'
version: 2.0.0+2

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.1
  cloud_firestore: ^5.6.1
  intl: ^0.19.0
  fl_chart: ^0.69.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  csv: ^6.0.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
